server:
  port: 80


spring:
  datasource:
    username: root
    password: rootCharles550
    url: jdbc:mysql://localhost:3306/event
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB



mybatis:
  table:
    auto: update
  model:
    pack: com.lantu.woevent.models
  database:
    type: mysql

mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
